// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

public class Cube : MonoBehaviour { 
	Rigidbody mRb;
	public static Vector3 mOriginalPosition;

	 void Start() { 
		mRb = GetComponent<Rigidbody> ();
		mOriginalPosition = transform.position;
		generateAndShootCubes ();
	}

	 void Update() { 
		shoot ();
		generateAndShootCubes ();
	}

	
	void shoot () {
		mRb.velocity = transform.TransformDirection(0, 0, -50f);
		mRb.AddForce(-(transform.forward * 10f));
	}
	
	void generateAndShootCubes () { 
		for (int i = 0; i < 100; i++) { 
			GameObject cube = GameObject.CreatePrimitive(PrimitiveType.Cube);
			cube.transform.position = new Vector3 (mOriginalPosition.x % 500f, 
			                                       mOriginalPosition.y % 500f, 
			                                       mOriginalPosition.z);
			Rigidbody rb = cube.AddComponent<Rigidbody> ();
			rb.velocity = transform.TransformDirection (0, 0, -50f);
			rb.AddForce (-(transform.forward * 10f));
		}
	}

	void onCollisionEnter(Collision col) { 

	}
}

